eurodatacube/eodash-catalog

- catalogs/race.yaml
- collections/E11_shopping_center_volume.yaml
- collections/E11a_parking_lot_volume.yaml
- collections/E12b_cruises_impact.yaml
- collections/N1b_O3.yaml
- collections/N1b_PM10.yaml
- collections/N1b_PM25.yaml
- collections/N1b_air_quality_NO2.yaml
- collections/N3c_ocean_colour_plankton_atlantic.yaml
- collections/N3c_ocean_colour_plankton_black_sea.yaml
- collections/N3c_ocean_colour_plankton_mediterranean.yaml
- collections/WSF_world_settlement_footprint.yaml
- generators/generate_indicators.py
- generators/utils.py
> Implemented overwrite possibility for wms times

- catalogs/race.yaml
- collections/CDS1_temperature.yaml
- collections/CDS2_relative_humidity.yaml
- collections/CDS3_wind_10m_u.yaml
- collections/CDS4_wind_10m_v.yaml
- collections/E12c_truck_detections_motorways.yaml
- collections/E12c_truck_detections_primary_roads.yaml
- collections/E13o_vessel_density_all.yaml
- collections/E13p_vessel_density_cargo.yaml
- collections/E13q_vessel_density_tanker.yaml
- collections/E13r_vessel_density_others.yaml
- collections/E3_oil_storage_volume.yaml
- collections/N1_CH4.yaml
- collections/N1_CO.yaml
- collections/N1_NO2.yaml
- collections/N1_SO2.yaml
- collections/N1b_NO2.yaml
- collections/N1b_O3.yaml
- collections/N1b_PM10.yaml
- collections/N1b_PM25.yaml
- collections/N3a2_chl_concentration.yaml
- collections/N3a2_sea_surface_temperature.yaml
- collections/N3a2_total_suspended_matter.yaml
- collections/N3c_ocean_colour_plankton_atlantic.yaml
- collections/N3c_ocean_colour_plankton_black_sea.yaml
- collections/N3c_ocean_colour_plankton_mediterranean.yaml
- collections/NASAPopulation.yaml
- generators/generate_indicators.py
added also legend assets to multiple collections
> added extra fields are added to collections

- collections/NPPN_net_primary_production.yaml
- generators/generate_indicators.py
changed some entries from comma separated string to array of string; updated citation to be correct
> minor fixes

- generators/generate_indicators.py
- Setting Bbox will filter SH STAC api request to said bbox
- Setting OverwriteBBox will independently of the included items overwrite the collection BBox
> added bbox manupilation possiblities for SH resources

- generators/generate_indicators.py
Adding new service endpoint and adding possibility to define assets
> Examples assets

- catalogs/race.yaml
- catalogs/trilateral.yaml
- collections/OW_Covid_19_vaccinations_trilateral.yaml
OW_Covid_19_vaccinations OW_Covid_19_vaccinations_trilateral
> add OW dataset

- catalogs/race.yaml
- collections/C1_ports_shipping_aq.yaml
- collections/C2_ports_cars_aq.yaml
- collections/C3_ports_people_aq.yaml
- generators/generate_indicators.py
- indicators/CAQ_ports_air_quality.yaml
- indicators/NO2_air_quality.yaml
CAQ_ports_air_quality NO2_air_quality NASAPopulation CDS1_temperature ADO_Alpine_Drought_Observatory_SPI1 ADO_1_Alpine_Drought_Observatory_SPI12 ADO_2_Alpine_Drought_Observatory_SPEI1 ADO_3_Alpine_Drought_Observatory_SPEI12 AQ1_aggregated_mobility_data_trajectories AQ1_1_aggregated_mobility_data_satellite_values AQ1_2_aggregated_mobility_data_mean_value AQ1_3_aggregated_mobility_data_congestion_index AQ1_4_aggregated_mobility_data_speed AQ1_5_aggregated_mobility_data_motorized_count AQ1_6_aggregated_mobility_data_motorized_share AQ2_NO2_Innsbruck_hot_spot_emissions AQ4_1_Human_Mobility_Patterns_Max_Duration AQ4_2_Human_Mobility_Patterns_Max_Speed AQ4_3_Human_Mobility_Patterns_Max_Distance AQ4_4_Human_Mobility_Patterns_Max_Trajectories AQ4_5_Human_Mobility_Patterns_Motorized_trip_share …
> feat: adding indicator level on top of collections

- catalogs/trilateral.yaml
- collections/E13b_parked_airplanes.yaml
- collections/EPA_Field_burning_Monthly.yaml
- collections/EPA_Forest_fire_Methane_Daily.yaml
- collections/EPA_Forest_fire_Methane_Yearly.yaml
- collections/EPA_Methane.yaml
- collections/HLS_NDVI.yaml
- collections/LIS_Global_DA_Evap.yaml
- collections/N1_NO2_diff_monthly.yaml
- collections/N1_NO2_monthly.yaml
- collections/N2_CO2_diff.yaml
- collections/N2_CO2_mean.yaml
- collections/N9_OMI_trno2-COG.yaml
- generators/generate_indicators.py
EPA_Methane HLS_NDVI LIS_Global_DA_Evap
> add 5 nasa biomass datasets

- collections/N1_CO.yaml
- collections/N1_NO2.yaml
- collections/N1_SO2.yaml
- collections/N1_city_no2.yaml
- collections/N1a_pm25_cams.yaml
- collections/N1b_NO2.yaml
- collections/N1b_O3.yaml
- collections/N1b_no2_cams.yaml
- collections/N1c_pm10_cams.yaml
- collections/N1d_o3_cams.yaml
N1_city_no2 N1_CO N1_NO2 N1_SO2 N1a_pm25_cams N1b_NO2 N1b_no2_cams N1b_O3 N1c_pm10_cams N1d_o3_cams
> YAML batch_5 update

- catalogs/race.yaml
- collections/E13c_ship_detections_algorithm.yaml
E13c_ship_detections_algorithm
> prepare E13c_ship_detections based on E200 as base

- collections/E10e_ndvi.yaml
- collections/sen4ama.yaml
> fix: adding media type and empty style to E10e and sen4ama collections

- catalogs/polar.yaml
- collections/Polartep_S1_demo.yaml
- collections/Polartep_SeaIceDetection_tif_demo.yaml
- collections/Polartep_SeaIce_demo.yaml
- collections/Polartep_Snow_specific_surface_area_demo.yaml
- collections/Polartep_Snowgrain_diameter_demo.yaml
- collections/TOPAZ4_P1D_SICONC.yaml
- collections/TOPAZ4_P1D_SISNTHICK.yaml
- collections/TOPAZ4_P1D_SITHICK.yaml
- collections/TOPAZ4_P1D_VXO.yaml
- collections/TOPAZ4_P1D_VXSI.yaml
- collections/TOPAZ4_P1D_VYO.yaml
- collections/TOPAZ4_P1D_VYSI.yaml
- collections/TOPAZ5_P1D_SIAGE.yaml
- collections/TOPAZ5_P1D_SICONC.yaml
- collections/TOPAZ5_P1D_SISNTHICK.yaml
- collections/TOPAZ5_P1D_SITHICK.yaml
- collections/TOPAZ5_P1D_VXO.yaml
- collections/TOPAZ5_P1D_VXSI.yaml
- collections/TOPAZ5_P1D_VYO.yaml
- collections/TOPAZ5_P1D_VYSI.yaml
- indicators/Polar_contributing_from_race.yaml
- indicators/Polar_demo_collections.yaml
- indicators/TOPAZ4_polar.yaml
- indicators/TOPAZ5_polar.yaml
Polar_contributing_from_race Polar_demo_collections TOPAZ5_polar TOPAZ4_polar
> restructure polar catalog with indicator grouping

- collections/E13b_parked_planes.yaml
- collections/GHS_BUILT-S-R2023A.yaml
- collections/OW_Covid_19_vaccinations.yaml
- collections/OX_Crude_Oil_Storage_Index.yaml
- collections/OX_EU_Crude_Oil_Storage_Index.yaml
- collections/SST_sea_surface_temperature.yaml
- collections/WSF_world_settlement_footprint.yaml
E13b_parked_planes GHS-BUILT-S-R2023A OW_Covid_19_vaccinations OX_Crude_Oil_Storage_Index OX_EU_Crude_Oil_Storage_Index SST_sea_surface_temperature WSF_world_settlement_footprint
> YAML batch_7 update

- generators/generate_indicators.py
RECCAP2_1_AGC_LVOD_amazonia_methods_mean_crop RECCAP2_2_AGC_LVOD_amazonia_smooth_max_crop RECCAP2_3_AGC_LVOD_amazonia_smooth_mean_crop RECCAP2_4_AGC_LVOD_amazonia_trend_mean_crop RECCAP2_5_SF_biomass_growth RECCAP2_6_deforested_biomass RECCAP2_7_degraded_biomass RECCAP2_8_edge_biomass_change RECCAP2_9_intact_biomass_change_methods_mean RECCAP2_10_intact_biomass_change_smooth_max RECCAP2_11_intact_biomass_change_smooth_mean RECCAP2_12_intact_biomass_change_trend_mean
> add xyz link to xcube datasets

- catalogs/race.yaml
- collections/E13o_vessel_density_all.yaml
- collections/E13p_vessel_density_cargo.yaml
- collections/E13q_vessel_density_tanker.yaml
- collections/E13r_vessel_density_others.yaml
- generators/generate_indicators.py
- indicators/BIPS_boats_in_ports.yaml
- indicators/CV19_covid_19_indicators.yaml
- indicators/GLP_global_parameters.yaml
- indicators/OCVA_ocean_variables.yaml
- indicators/VED_vessel_density.yaml
- indicators/WAQ_water_quality.yaml
C3S_meteorological_variables E11_shopping_center_activity E11_shopping_center_volume E12b_border_crossing_vehicles_timeseries E12c_truck_detections_motorways E12d_truck_detections_primary_roads E13b_airport_throughput E13b_parked_planes E13c_cruises_impact E13d_flying_planes VED_vessel_density E200_ships_detected E3_crude_oil_storage E4_intermediate_goods_production E5_steel_inventory_timeseries OCVA_ocean_variables WAQ_water_quality NASAPopulation WSF_world_settlement_footprint CAQ_ports_air_quality E8_industrial_inventory APRO_agricultural_production AQEL_air_quality_european_level BIPS_boats_in_ports E13n_trucks_port E13c_ship_detections_algorithm GHS_BUILT-S-R2023A OX_Crude_Oil_Storage_Index OX_EU_Crude_Oil_Storage_Index GG_people_mobility_reports CV19_covid_19_indicators …
> Final indicators update

- catalogs/polar.yaml
- catalogs/trilateral.yaml
- collections/4D_Greenland_Duration.yaml
- collections/4D_Greenland_Melt_Onset.yaml
- collections/4D_Greenland_Melt_Season_End.yaml
- collections/4D_Greenland_Meltmap.yaml
- collections/ADD_Melt_Duration.yaml
- collections/ADD_Melt_Onset.yaml
- collections/ADD_Melt_Season_End.yaml
- indicators/4D_Greenland.yaml
ADD_Melt_Duration 4D_Greenland ADD_Melt_Season_End ADD_Melt_Onset ADD_Meltmap
> adding 4D_Greenland datasets and

- catalogs/trilateral.yaml
- collections/GFC_Garissa_FloodExtent.yaml
- generators/generate_indicators.py
- generators/utils.py
> feat: implemented new resource type geojson sources

- collections/E10c_rice_planting.yaml
- collections/E10d_regional_cropland.yaml
- collections/E10e_ndvi.yaml
- collections/E9_car_containers.yaml
- collections/FNF_Palsar.yaml
- collections/facebook_population_density.yaml
- collections/grdi-shdi-raster.yaml
- collections/grdi-v1-built.yaml
- collections/grdi-v1-raster.yaml
- collections/grdi-vnl-slope-raster.yaml
E9_car_containers E10c_rice_planting E10d_regional_cropland E10e_ndvi facebook_population_density FNF_Palsar grdi-shdi-raster grdi-v1-built grdi-v1-raster grdi-vnl-slope-raster
> YAML batch_8 update

- collections/Lakes_ALOS2_HH.yaml
- collections/Lakes_ALOS2_HV.yaml
- collections/Lakes_S2L2A.yaml
- collections/Lakes_SWT.yaml
- collections/Lakes_Sentinel1.yaml
- collections/Lakes_WQ_TC_water_quality.yaml
- collections/grdi-cdr-raster.yaml
- collections/grdi-filled-missing-values-count.yaml
- collections/grdi-imr-raster.yaml
- collections/grdi-vnl-raster.yaml
grdi-cdr-raster grdi-filled-missing-values-count grdi-imr-raster grdi-vnl-raster Lakes_ALOS2_HH Lakes_ALOS2_HV Lakes_S2L2A Lakes_Sentinel1 Lakes_SWT Lakes_WQ_TC_water_quality
> YAML batch_9 update

- collections/E10a10_2_harvesting_evolution_winter_rapeseed.yaml
- collections/E10a10_harvesting_evolution_winter_cereal.yaml
- indicators/APRO_agricultural_production.yaml
> chore: split harvesting evolution into two collections

- generators/generate_indicators.py
ADO_Alpine_Drought_Observatory_SPI1  4D_Greenland E12c_truck_detections_motorways N1_NO2_diff_monthly
> Catalog self link

- catalogs/trilateral.yaml
- collections/crop_forecast_CropOM_AT.yaml
- collections/crop_forecast_CropOM_HU.yaml
- collections/crop_forecast_CropOM_HU_microregion.yaml
- collections/crop_forecast_CropOM_HU_subcounty.yaml
- collections/crop_forecast_CropOM_RO.yaml
- indicators/crop_forecast_CropOM.yaml
> add new cropom data yamls

- collections/N3c_ocean_colour_plankton_atlantic.yaml
- collections/N3c_ocean_colour_plankton_black_sea.yaml
- collections/N3c_ocean_colour_plankton_mediterranean.yaml
> fix N3c new endpoints

- collections/LWE_lake_water_extent.yaml
- collections/LWL_lake_water_level.yaml
- collections/Lakes_WQ_TURB_water_turbidity.yaml
- collections/N10_OMSO2PCA-COG.yaml
- collections/N11_ocean_primary_productivity.yaml
- collections/N12_1_sea_ice_concentration_arctic.yaml
- collections/N1_NO2_city_trilateral.yaml
- collections/N1_NO2_diff_monthly.yaml
- collections/N1_NO2_jaxa.yaml
- collections/N1_NO2_monthly.yaml
Lakes_WQ_TURB_water_turbidity LWE_lake_water_extent LWL_lake_water_level N1_NO2_city_trilateral N1_NO2_diff_monthly N1_NO2_jaxa N1_NO2_monthly N10_OMSO2PCA-COG N11_ocean_primary_productivity N12_1_sea_ice_concentration_arctic
> YAML batch_10 update

- collections/ESDC_gross_primary_productivity.yaml
- collections/ESDC_kndvi.yaml
- collections/ESDC_net_ecosystem_exchange.yaml
- collections/GGI_CH4.yaml
- collections/GGI_CO2.yaml
- collections/GGI_N2O.yaml
- collections/RECCAP2_10_intact_biomass_change_smooth_max.yaml
- collections/RECCAP2_11_intact_biomass_change_smooth_mean.yaml
- collections/RECCAP2_12_intact_biomass_change_trend_mean.yaml
- collections/RECCAP2_1_AGC_LVOD_amazonia_methods_mean_crop.yaml
- collections/RECCAP2_2_AGC_LVOD_amazonia_smooth_max_crop.yaml
- collections/RECCAP2_3_AGC_LVOD_amazonia_smooth_mean_crop.yaml
- collections/RECCAP2_4_AGC_LVOD_amazonia_trend_mean_crop.yaml
- collections/RECCAP2_5_SF_biomass_growth.yaml
- collections/RECCAP2_6_deforested_biomass.yaml
- collections/RECCAP2_7_degraded_biomass.yaml
- collections/RECCAP2_8_edge_biomass_change.yaml
- collections/RECCAP2_9_intact_biomass_change_methods_mean.yaml
RECCAP2_1_AGC_LVOD_amazonia_methods_mean_crop RECCAP2_2_AGC_LVOD_amazonia_smooth_max_crop RECCAP2_3_AGC_LVOD_amazonia_smooth_mean_crop RECCAP2_4_AGC_LVOD_amazonia_trend_mean_crop RECCAP2_5_SF_biomass_growth RECCAP2_6_deforested_biomass RECCAP2_7_degraded_biomass RECCAP2_8_edge_biomass_change RECCAP2_9_intact_biomass_change_methods_mean RECCAP2_10_intact_biomass_change_smooth_max RECCAP2_11_intact_biomass_change_smooth_mean RECCAP2_12_intact_biomass_change_trend_mean ESDC_gross_primary_productivity ESDC_kndvi ESDC_net_ecosystem_exchange GGI_CH4 GGI_CO2 GGI_N2O
> YAML batch_13 update

- catalogs/race.yaml
- catalogs/trilateral.yaml
- collections/ESDL_Hydrology_Precipitation.yaml
- collections/ESDL_Hydrology_SM.yaml
ESDL_Hydrology_SM ESDL_Hydrology_Precipitation
> feat: add ESDL Hydrology Soil Moisture and Precipitation

- README.md
- catalogs/trilateral.yaml
- collections/Modis_SNPP_2023.yaml
- collections/N1_CO.yaml
- collections/VIIRS_SNPP_2023.yaml
> add VIIRs Fire Detections

- collections/NLK_lake_aral.yaml
- collections/NPPN_net_primary_production.yaml
- collections/NPP_ocean_primary_productivity.yaml
- collections/PRCG_precipitation.yaml
- collections/PRCTS_precipitation_timeseries.yaml
- collections/PRC_precipitation_anomaly.yaml
- collections/SIC_sea_ice_thickness_cryosat.yaml
- collections/SIE_sea_ice_thickness_envisat.yaml
- collections/SIF_solar_induced_chlorophyll_fluorescence.yaml
- collections/SITI_IS2SITMOGR4-cog.yaml
- collections/SMCG_soil_moisture_content.yaml
- collections/SMCTS_soil_moisture_timeseries.yaml
- collections/SMC_soil_moisture_anomaly.yaml
- collections/VITS_vegetation_index_timeseries.yaml
- collections/nceo_africa_2017.yaml
nceo_africa_2017 NLK_lake_aral NPP_ocean_primary_productivity NPPN_net_primary_production PRC_precipitation_anomaly PRCG_precipitation PRCTS_precipitation_timeseries SIC_sea_ice_thickness_cryosat SIE_sea_ice_thickness_envisat SIF_solar_induced_chlorophyll_fluorescence SITI_IS2SITMOGR4-cog SMC_soil_moisture_anomaly SMCG_soil_moisture_content SMCTS_soil_moisture_timeseries VITS_vegetation_index_timeseries
> YAML batch_12 update

- collections/N12_sea_ice_concentration_antarctic.yaml
- collections/N2_CO2_diff.yaml
- collections/N2_CO2_jaxa_gosat.yaml
- collections/N2_CO2_mean.yaml
- collections/N2_greenhouse_gases.yaml
- collections/N5_nightlights.yaml
- collections/N6_geoglam.yaml
- collections/N7_slowdown_proxy.yaml
- collections/N8_recovery_proxy.yaml
- collections/N9_OMI_trno2-COG.yaml
N2_CO2_diff N2_CO2_jaxa_gosat N2_CO2_mean N2_greenhouse_gases N5_nightlights N6_geoglam N7_slowdown_proxy N8_recovery_proxy N9_OMI_trno2-COG N12_sea_ice_concentration_antarctic
> YAML batch_11 update

- collections/N1_NO2_trilateral.yaml
- generators/generate_indicators.py
> Paralelize collections generation

- README.md
- collections/N12_1_sea_ice_concentration_arctic.yaml
- collections/N12_sea_ice_concentration_antarctic.yaml
- collections/Polartep_S2_segmentation.yaml
- indicators/Polar_demo_collections.yaml
Polar_contributing_from_race Polar_demo_collections TOPAZ5_polar TOPAZ4_polar 4D_Greenland
> add polardashboard_s2_segmentation

- .github/workflows/build_main.yaml
- .github/workflows/build_pull_request.yaml
> bump version of eodash_catalog to 0.0.32

- catalogs/trilateral.yaml
- collections/NTLR_JAXA_Nighttimelevel_Rural.yaml
- collections/NTLU_JAXA_Nighttimelevel_Urban.yaml
NTLR_JAXA_Nighttimelevel_Rural NTLU_JAXA_Nighttimelevel_Urban
> Add the JAXA night lights indicators

- catalogs/trilateral.yaml
- collections/SSLC1_Seasonal_S1_AMP_hv_interferometric_coherence.yaml
- collections/SSLC2_Seasonal_S1_COH12_hh_interferometric_coherence.yaml
SSLC1_Seasonal_S1_AMP_hv_interferometric_coherence SSLC2_Seasonal_S1_COH12_hh_interferometric_coherence OHC300_Ocean_Heat_Content_upper_300m NELST_ECOSTRESS_LST
> fix: adding missing collections to catalog definition

- catalogs/race.yaml
- collections/CNR_TUR_1_water_discharge.yaml
- collections/RCM_TUR_1_water_discharge.yaml
> CNR data integration

- collections/E10e_ndvi.yaml
- collections/N11_ocean_primary_productivity.yaml
- collections/N12_1_sea_ice_concentration_arctic.yaml
- collections/N12_sea_ice_concentration_antarctic.yaml
- collections/N1_NO2_jaxa.yaml
- collections/N2_CO2_jaxa_gosat.yaml
- collections/PRCG_precipitation.yaml
- collections/PRC_precipitation_anomaly.yaml
- collections/SIF_solar_induced_chlorophyll_fluorescence.yaml
- collections/SMCG_soil_moisture_content.yaml
- collections/SMC_soil_moisture_anomaly.yaml
SIF_solar_induced_chlorophyll_fluorescence PRCG_precipitation N11_ocean_primary_productivity PRC_precipitation_anomaly N1_NO2_jaxa N12_1_sea_ice_concentration_arctic N12_sea_ice_concentration_antarctic SMCG_soil_moisture_content SMC_soil_moisture_anomaly E10e_ndvi N2_CO2_jaxa_gosat
> chore: change all jaxa layers endpoint and names
